"""Authentication and authorization helpers for the FastAPI application."""

from datetime import datetime, timedelta
from typing import Annotated

from fastapi import Depends, HTTPException, Request, status
from fastapi.security import OAuth2PasswordBearer
from jose import JWTError, jwt
from passlib.context import CryptContext

from acebet.app.config import settings

from .data_models import TokenData, UserInDB

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")
SECRET_KEY = settings.secret_key
ALGORITHM = settings.algorithm
ACCESS_TOKEN_EXPIRE_MINUTES = settings.access_token_expire_minutes

fake_users_db = {
    "johndoe": {
        "username": "johndoe",
        "full_name": "John Doe",
        "email": "johndoe@example.com",
        "hashed_password": (
            "$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW"
        ),
        "disabled": False,
    }
}

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Validate a plaintext password against a bcrypt hash.

    Args:
        plain_password: Plaintext password provided by a user.
        hashed_password: Stored password hash.

    Returns:
        bool: ``True`` when the password matches the hash.
    """
    return pwd_context.verify(plain_password, hashed_password)


def get_password_hash(password: str) -> str:
    """Generate a password hash for persistent storage.

    Args:
        password: Plaintext password to hash.

    Returns:
        str: Hash generated by the configured ``CryptContext``.
    """
    return pwd_context.hash(password)


def get_user(db: dict[str, dict], username: str) -> UserInDB | None:
    """Fetch a user record from an in-memory database mapping.

    Args:
        db: User dictionary keyed by username.
        username: Username to resolve.

    Returns:
        UserInDB | None: Parsed user model when found, otherwise ``None``.
    """
    if username in db:
        user_dict = db[username]
        return UserInDB(**user_dict)
    return None


def authenticate_user(
    fake_db: dict[str, dict], username: str, password: str
) -> UserInDB | bool:
    """Authenticate a user against the in-memory credentials store.

    Args:
        fake_db: User dictionary keyed by username.
        username: Submitted username.
        password: Submitted plaintext password.

    Returns:
        UserInDB | bool: User model when valid, otherwise ``False``.
    """
    user = get_user(fake_db, username)
    if not user:
        return False
    if not verify_password(password, user.hashed_password):
        return False
    return user


def create_access_token(data: dict, expires_delta: timedelta | None = None) -> str:
    """Encode an access token with an expiration claim.

    Args:
        data: Claims to include in the token payload.
        expires_delta: Optional custom expiration duration.

    Returns:
        str: Signed JWT access token.
    """
    to_encode = data.copy()
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(minutes=15)
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt


def get_current_user(token: Annotated[str, Depends(oauth2_scheme)]) -> UserInDB:
    """Resolve and validate the authenticated user from a bearer token.

    Args:
        token: JWT bearer token extracted from the request.

    Returns:
        UserInDB: Authenticated user model.

    Raises:
        HTTPException: If token decoding fails or user lookup fails.
    """
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username: str | None = payload.get("sub")
        if username is None:
            raise credentials_exception
        token_data = TokenData(username=username)
    except JWTError as exc:
        raise credentials_exception from exc

    user = get_user(fake_users_db, username=token_data.username)
    if user is None:
        raise credentials_exception
    return user


def get_current_active_user(
    current_user: UserInDB = Depends(get_current_user),
) -> UserInDB:
    """Ensure the current authenticated user is not disabled.

    Args:
        current_user: User resolved by ``get_current_user``.

    Returns:
        UserInDB: Active user model.

    Raises:
        HTTPException: If the user is marked as disabled.
    """
    if current_user.disabled:
        raise HTTPException(status_code=400, detail="Inactive user")
    return current_user


def get_user_identifier(
    request: Request, current_user: UserInDB = Depends(get_current_user)
) -> str:
    """Return the rate-limiting identifier for the current request.

    Args:
        request: Incoming request object.
        current_user: Authenticated user model.

    Returns:
        str: Username used as a rate-limit key.
    """
    del request
    return current_user.username
