name: testing

on:
  push:
    branches:
      - "main"
jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Lint docstrings
        run: |
          uv run ruff check \
            src/acebet/app/main.py \
            src/acebet/app/dependencies \
            src/acebet/train/train.py \
            src/acebet/dataprep/dataprep.py \
            src/acebet/__init__.py

      - name: Run tests
        run: uv run pytest tests
